In [2]:
import numpy as np

Heading 1
=========
The above ___cell___ is printing hello
--------------------------------------

# Heading 2

In [3]:
myarray = np.array([[1,2],[2,3],[3,4],[4,5],[5,6],[6,5]],dtype = float)
myarray

array([[1., 2.],
       [2., 3.],
       [3., 4.],
       [4., 5.],
       [5., 6.],
       [6., 5.]])

In [4]:

print("Rows: ",np.shape(myarray)[0])
print("Columns: ",np.shape(myarray)[1])

Rows:  6
Columns:  2


In [5]:
myarray.dtype

dtype('float64')

In [6]:
b = np.arange(0,200,10).reshape(4,5)

In [7]:
np.shape(b)

(4, 5)

In [8]:
b

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.dtype

dtype('int64')

In [11]:
myarray.dtype

dtype('float64')

In [12]:
print(b[:3,:3])

[[  0  10  20]
 [ 50  60  70]
 [100 110 120]]


In [13]:
zerosArray = np.ones((3,6),int)

In [14]:
zerosArray

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [15]:
zerosArray.dtype

dtype('int64')

In [38]:
b

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [36]:
b[(b < 100)] = 0

In [37]:
b

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [42]:
b.transpose()
b

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [40]:
b.flatten()

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [41]:
b.flatten("F")

array([  0,   0, 100, 150,   0,   0, 110, 160,   0,   0, 120, 170,   0,
         0, 130, 180,   0,   0, 140, 190])