In [110]:
import numpy as np
from numpy import random

In [111]:
my_list = [1,2,3,4,5,6,8,9,0,55,7,8,55,3,44,2]
type(my_list)

list

In [112]:
np_array = np.array(my_list)
np_array.dtype

# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short
# Long : np.int_
# Float : np.single & np.float32
# Double : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

np_array1 = np.array([[[1,2,5],[2,7,8],[4,5,6,]],[[4,1,4],[5,7,9],[7,8,3]],[[3,7,9],[5,1,4],[7,6,7]]])
print(np_array1)
print(np_array1.shape)

np_array1.ndim

print("row1:",np_array1.shape[0])
print("row2:",np_array1.shape[1])
print("column:",np_array1.shape[2])



[[[1 2 5]
  [2 7 8]
  [4 5 6]]

 [[4 1 4]
  [5 7 9]
  [7 8 3]]

 [[3 7 9]
  [5 1 4]
  [7 6 7]]]
(3, 3, 3)
row1: 3
row2: 3
column: 3


In [113]:
np_array.ndim
np_array.shape


(16,)

In [114]:
print(np_array)
np_array.reshape(4,2,2).ndim

[ 1  2  3  4  5  6  8  9  0 55  7  8 55  3 44  2]


3

In [115]:
np_array2 = np.arange(1,100,2)
np_array2.reshape(5,5,2)

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]],

       [[21, 23],
        [25, 27],
        [29, 31],
        [33, 35],
        [37, 39]],

       [[41, 43],
        [45, 47],
        [49, 51],
        [53, 55],
        [57, 59]],

       [[61, 63],
        [65, 67],
        [69, 71],
        [73, 75],
        [77, 79]],

       [[81, 83],
        [85, 87],
        [89, 91],
        [93, 95],
        [97, 99]]])

In [116]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [117]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [118]:
np.eye(2,2,dtype = int)

array([[1, 0],
       [0, 1]])

In [119]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [120]:
np.random.randint([100,100])

array([52, 59], dtype=int32)

In [121]:
np_array4 = np.random.randint(50,100, size = (5,5))
print(np_array4*3)

[[204 162 246 210 207]
 [270 204 243 234 240]
 [207 207 249 273 183]
 [291 294 249 252 237]
 [231 282 168 177 276]]


In [122]:
np_array4.flatten("F")

array([68, 90, 69, 97, 77, 54, 68, 69, 98, 94, 82, 81, 83, 83, 56, 70, 78,
       91, 84, 59, 69, 80, 61, 79, 92], dtype=int32)

In [123]:
even = np_array4[(np_array4%2==0) & (np_array4>50)]

In [124]:
print(even)

[68 54 82 70 90 68 78 80 98 84 94 56 92]


In [126]:
print(even.size)
if even.size%2 !=0:
    even = np.append(even,[np.nan])
    print(even)
even.reshape(2,int(len(even)/2))

14


array([[68, 54, 82, 70, 90, 68, 78],
       [80, 98, 84, 94, 56, 92,  0]])

# Linespaces

In [133]:
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Unique Elements

In [135]:
print(np_array4)
np.unique(np_array4)

[[68 54 82 70 69]
 [90 68 81 78 80]
 [69 69 83 91 61]
 [97 98 83 84 79]
 [77 94 56 59 92]]


array([54, 56, 59, 61, 68, 69, 70, 77, 78, 79, 80, 81, 82, 83, 84, 90, 91,
       92, 94, 97, 98], dtype=int32)

# Reshaping Arrays

In [159]:
np_array5 = np.random.randint(0,10,size = (4,5))
# np_array5.reshape(2,2,25)
# np_array5.resize(2,50)
print(np_array5)
np_array5.transpose()
np_array5.swapaxes(1,0)
np_array5.sort(axis = 1)
np_array5

[[9 3 4 8 8]
 [4 6 0 9 4]
 [5 4 9 0 2]
 [7 4 6 8 1]]


array([[3, 4, 8, 8, 9],
       [0, 4, 4, 6, 9],
       [0, 2, 4, 5, 9],
       [1, 4, 6, 7, 8]], dtype=int32)

# Stacking & Splitting

In [256]:
np_array6 = np.random.randint(0,10,size = (4,10))
print("np_array6",np_array6)
np_array7 = np.random.randint(0,10,size = (4,10))
print("np_array7",np_array7)

np.vstack((np_array6,np_array7))
np.hstack((np_array6,np_array7))

# np_array8 = np.delete(np_array6,2,0)
np_array8 = np.delete(np_array6,1,1)
np_array8

# np.column_stack((np_array6,np_array7))
# np.row_stack((np_array6,np_array7))


np.vsplit(np_array6, 2)

# np.split?






np_array6 [[2 0 9 6 1 8 3 3 1 4]
 [4 9 4 5 1 9 0 0 4 2]
 [5 7 1 7 8 1 7 7 0 0]
 [4 1 9 4 0 2 1 7 6 9]]
np_array7 [[8 6 0 4 1 0 6 2 5 1]
 [7 3 4 3 1 4 0 9 7 0]
 [9 6 0 1 2 6 2 9 0 4]
 [5 3 8 6 3 8 7 8 7 1]]


[array([[2, 0, 9, 6, 1, 8, 3, 3, 1, 4],
        [4, 9, 4, 5, 1, 9, 0, 0, 4, 2]], dtype=int32),
 array([[5, 7, 1, 7, 8, 1, 7, 7, 0, 0],
        [4, 1, 9, 4, 0, 2, 1, 7, 6, 9]], dtype=int32)]

# Copying

In [205]:

np_array8 = np_array6
# np_array8.resize(4,5)

print("np_array6",np_array6)
print("np_array6",np_array8)

cp_array = np_array6.view()
print(cp_array.flatten())

# cp_array.resize((2,4))
print("cp_array",cp_array)
cp_array1 = np_array6.copy()

cp_array1.resize((4,5))


np_array6 [[3 8 4 8 6 2 3 1 8 8]
 [5 4 0 1 2 6 2 6 0 1]
 [4 6 5 7 8 2 9 0 9 0]
 [2 8 0 3 3 3 2 1 8 8]]
np_array6 [[3 8 4 8 6 2 3 1 8 8]
 [5 4 0 1 2 6 2 6 0 1]
 [4 6 5 7 8 2 9 0 9 0]
 [2 8 0 3 3 3 2 1 8 8]]
[3 8 4 8 6 2 3 1 8 8 5 4 0 1 2 6 2 6 0 1 4 6 5 7 8 2 9 0 9 0 2 8 0 3 3 3 2
 1 8 8]
cp_array [[3 8 4 8 6 2 3 1 8 8]
 [5 4 0 1 2 6 2 6 0 1]
 [4 6 5 7 8 2 9 0 9 0]
 [2 8 0 3 3 3 2 1 8 8]]


# Math

In [280]:
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])
print("arr_4",arr_4)

arr_3 + arr_4

arr_3 - arr_4

arr_3 * arr_4

arr_3 / arr_4

arr_3 % arr_4

random.choice(arr_4)

arr_4.sum()

arr_6 = random.randint(100, size=(2, 3))
print(arr_6)

arr_6.cumsum(axis = 1)

arr_6.min()

arr_6.max()

max_values = arr_6.argmax(axis = 0)

np.add(arr_3,arr_4)

np.subtract(arr_3,arr_4)

np.power(arr_3,arr_4)

np.sqrt(arr_4)

np.cbrt(arr_4)

np.absolute([-2,-5,6,9.9])

np.exp(arr_4)
np.floor([1.3,5.9,10.0]) #round down
np.ceil([1.3,5.9,10.0]) #round up

print(arr_6.shape)



arr_4 [2 4 6 8]
[[35 94 81]
 [25 46 15]]
(2, 3)


In [324]:
Student_data = {"st-1":{"Maths":80,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60},
               "st-2":{"Maths":80,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60},
               "st-3":{"Maths":80,"Urdu":70,"Sindhi":95,"Chemistry":90,"Physics":60},
               "st-4":{"Maths":80,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60},
               "st-5":{"Maths":80,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60}}
st_Id = np.array([key for key in Student_data.keys()])
st_array = np.array([list(value.values()) for value in Student_data.values()])
subjects = np.array([list(key.keys()) for key in Student_data.values()])[0]


print(subjects)
print(st_Id)
print(st_array)



['Maths' 'Urdu' 'Sindhi' 'Chemistry' 'Physics']
['st-1' 'st-2' 'st-3' 'st-4' 'st-5']
[[80 70 40 90 60]
 [80 70 40 90 60]
 [80 70 95 90 60]
 [80 70 40 90 60]
 [80 70 40 90 60]]

**********
Rank:0
Student Id: st-3
Subject with high score: Sindhi
Score: 2
**********
**********
Rank:1
Student Id: st-1
Subject with high score: Maths
Score: 3
**********
**********
Rank:2
Student Id: st-2
Subject with high score: Urdu
Score: 3
**********
**********
Rank:3
Student Id: st-4
Subject with high score: Chemistry
Score: 3
**********
**********
Rank:4
Student Id: st-5
Subject with high score: Physics
Score: 3
**********
